spring:
  codec:
    log-request-details: true
  datasource:
    url: jdbc:postgresql://localhost:5432/mydatabase
    username: postgres
    password: postgres
  sql:
    init:
      mode: always
      schema-locations: classpath:sql/schema/*sql
jwt:
  key:
    id: bootiful-key
  persistence:
    password: password
    salt: 626F6F746966756C
logging:
  level:
    root: info
    web: debug
    org.springframework.security: trace
    dev.hobie.authorization_service: debug
